<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260915220733 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial Woningtriage schema: intakes, reports, tokens, classification.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE access_token (id VARCHAR(64) NOT NULL, token_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B6A2DD68B3BC57DA ON access_token (token_hash)');
        $this->addSql('CREATE INDEX IDX_B6A2DD68B3BC57DA ON access_token (token_hash)');
        $this->addSql('CREATE INDEX IDX_B6A2DD68A76ED395 ON access_token (user_id)');
        $this->addSql('CREATE TABLE activation_code (id VARCHAR(64) NOT NULL, code_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FA574C9AE7530879 ON activation_code (code_hash)');
        $this->addSql('CREATE INDEX IDX_FA574C9AA76ED395 ON activation_code (user_id)');
        $this->addSql('CREATE TABLE analysis_task (id VARCHAR(64) NOT NULL, type VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, base_revision INT NOT NULL, result_revision INT DEFAULT NULL, error JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, intake_id VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_63CD9ECE733DE4507B00651C ON analysis_task (intake_id, status)');
        $this->addSql('CREATE INDEX IDX_63CD9ECE733DE450 ON analysis_task (intake_id)');
        $this->addSql('CREATE TABLE app_user (id VARCHAR(64) NOT NULL, label VARCHAR(120) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE classification_node (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tree_version VARCHAR(64) NOT NULL, level VARCHAR(16) NOT NULL, source_value VARCHAR(64) NOT NULL, label VARCHAR(255) NOT NULL, normalized_label VARCHAR(255) NOT NULL, path_key VARCHAR(512) NOT NULL, parent_path_key VARCHAR(512) DEFAULT NULL, competence_id VARCHAR(64) DEFAULT NULL, source_planning_duration DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1CAE7FB759B71DE9AEACC13 ON classification_node (tree_version, level)');
        $this->addSql('CREATE INDEX IDX_1CAE7FB759B71DED2F9E258 ON classification_node (tree_version, normalized_label)');
        $this->addSql('CREATE UNIQUE INDEX uniq_class_path ON classification_node (tree_version, path_key)');
        $this->addSql('CREATE TABLE idempotency_record (id VARCHAR(64) NOT NULL, actor_id VARCHAR(64) NOT NULL, intake_id VARCHAR(64) NOT NULL, operation VARCHAR(64) NOT NULL, idempotency_key VARCHAR(128) NOT NULL, payload_hash VARCHAR(64) NOT NULL, status_code INT NOT NULL, response_body JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_idempotency ON idempotency_record (actor_id, intake_id, operation, idempotency_key)');
        $this->addSql('CREATE TABLE intake (id VARCHAR(64) NOT NULL, revision INT NOT NULL, status VARCHAR(32) NOT NULL, tree_version VARCHAR(64) NOT NULL, prompt_version VARCHAR(64) NOT NULL, conversation_language VARCHAR(32) NOT NULL, language_mode VARCHAR(16) NOT NULL, document JSON NOT NULL, report_id VARCHAR(64) DEFAULT NULL, demo BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, owner_id VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AEA2877A7E3C61F9 ON intake (owner_id)');
        $this->addSql('CREATE TABLE intake_event (id VARCHAR(64) NOT NULL, sequence INT NOT NULL, type VARCHAR(64) NOT NULL, revision INT NOT NULL, payload JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, intake_id VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_intake_event_seq ON intake_event (intake_id, sequence)');
        $this->addSql('CREATE INDEX IDX_2C6D05FA733DE450 ON intake_event (intake_id)');
        $this->addSql('CREATE TABLE intake_message (id VARCHAR(64) NOT NULL, sequence INT NOT NULL, speaker VARCHAR(16) NOT NULL, language VARCHAR(32) NOT NULL, text TEXT NOT NULL, origin VARCHAR(32) NOT NULL, provisional BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, intake_id VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_29171934733DE4505286D72B ON intake_message (intake_id, sequence)');
        $this->addSql('CREATE INDEX IDX_29171934733DE450 ON intake_message (intake_id)');
        $this->addSql('CREATE TABLE report (id VARCHAR(64) NOT NULL, source_revision INT NOT NULL, payload JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, intake_id VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_report_intake ON report (intake_id)');
        $this->addSql('CREATE TABLE voice_session (id VARCHAR(64) NOT NULL, provider_session_id VARCHAR(128) DEFAULT NULL, status VARCHAR(32) NOT NULL, transport VARCHAR(32) NOT NULL, sdp_answer TEXT DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, close_reason VARCHAR(64) DEFAULT NULL, usage_finalized BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, intake_id VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_89302E47733DE4507B00651C ON voice_session (intake_id, status)');
        $this->addSql('CREATE INDEX IDX_89302E47733DE450 ON voice_session (intake_id)');
        $this->addSql('ALTER TABLE access_token ADD CONSTRAINT FK_B6A2DD68A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activation_code ADD CONSTRAINT FK_FA574C9AA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analysis_task ADD CONSTRAINT FK_63CD9ECE733DE450 FOREIGN KEY (intake_id) REFERENCES intake (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE intake ADD CONSTRAINT FK_AEA2877A7E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE intake_event ADD CONSTRAINT FK_2C6D05FA733DE450 FOREIGN KEY (intake_id) REFERENCES intake (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE intake_message ADD CONSTRAINT FK_29171934733DE450 FOREIGN KEY (intake_id) REFERENCES intake (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784733DE450 FOREIGN KEY (intake_id) REFERENCES intake (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE voice_session ADD CONSTRAINT FK_89302E47733DE450 FOREIGN KEY (intake_id) REFERENCES intake (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE access_token DROP CONSTRAINT FK_B6A2DD68A76ED395');
        $this->addSql('ALTER TABLE activation_code DROP CONSTRAINT FK_FA574C9AA76ED395');
        $this->addSql('ALTER TABLE analysis_task DROP CONSTRAINT FK_63CD9ECE733DE450');
        $this->addSql('ALTER TABLE intake DROP CONSTRAINT FK_AEA2877A7E3C61F9');
        $this->addSql('ALTER TABLE intake_event DROP CONSTRAINT FK_2C6D05FA733DE450');
        $this->addSql('ALTER TABLE intake_message DROP CONSTRAINT FK_29171934733DE450');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784733DE450');
        $this->addSql('ALTER TABLE voice_session DROP CONSTRAINT FK_89302E47733DE450');
        $this->addSql('DROP TABLE access_token');
        $this->addSql('DROP TABLE activation_code');
        $this->addSql('DROP TABLE analysis_task');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE classification_node');
        $this->addSql('DROP TABLE idempotency_record');
        $this->addSql('DROP TABLE intake');
        $this->addSql('DROP TABLE intake_event');
        $this->addSql('DROP TABLE intake_message');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE voice_session');
    }
}
